### ISSUE TITLE
这是公用的吗

### ISSUE THREAD

**Issue by zmlf** [JupiterH/Quantumult-X#1]
https://github.com/JupiterH/Quantumult-X/blob/9a86ead4740d0e65916a4940cdef51eef2bbe476/QuantumultX_Profiles.conf#L51

**Comment by JupiterH** [comment]
这是我个人备份使用的，不是公用

998548xyz ***@***.***> 于2022年12月12日周一 17:51写道：

**Comment by JupiterH** [comment]
啊这，刚刚一看，忘把订阅链接去掉了

998548xyz ***@***.***> 于2022年12月12日周一 17:51写道：
